import os

import requests
import streamlit as st

API_URL = os.getenv("RAG_API_URL", "http://localhost:8001").rstrip("/")
QUERY_URL = f"{API_URL}/query"

st.set_page_config(
    page_title="Enterprise RAG Assistant",
    page_icon="📚",
    layout="wide",
)

st.title("📚 Enterprise RAG Assistant")
st.caption(
    "Ask questions across HR, Finance, Legal, and Customer documents."
)

with st.sidebar:
    st.header("Search settings")
    st.selectbox(
        "Department",
        ["All Departments", "HR", "Finance", "Legal", "Customer"],
        key="department_filter",
    )
    st.caption("Answers are generated by the connected RAG backend.")
    st.caption(f"Backend: {API_URL}")

st.subheader("Ask your question")

question = st.text_area(
    "Enter a question about your documents",
    placeholder="Example: What is the leave policy?",
    height=120,
)

if st.button("Search documents", type="primary"):
    if not question.strip():
        st.warning("Please enter a question first.")
    else:
        try:
            with st.spinner(
                "Searching documents and generating an answer… "
                "This may take 15–60 seconds."
            ):
                response = requests.post(
                    QUERY_URL,
                    json={"question": question.strip()},
                    timeout=120,
                )

            if response.status_code == 200:
                data = response.json()

                st.session_state["rag_answer"] = data.get(
                    "answer", "No answer was returned."
                )
                st.session_state["rag_department"] = data.get(
                    "department", "unknown"
                )
                st.session_state["rag_sources"] = data.get("sources", [])

            else:
                st.error(
                    f"Backend error (HTTP {response.status_code}). "
                    "Please try again."
                )

        except requests.exceptions.ConnectionError:
            st.error(
                "Can't reach the RAG server. "
                "Please check that the backend is running on port 8001."
            )

        except requests.exceptions.Timeout:
            st.error(
                "The request took too long. "
                "Please check the backend and try again."
            )

        except requests.exceptions.RequestException:
            st.error("Something went wrong while contacting the backend.")

        except ValueError:
            st.error("The backend returned an invalid response.")

if "rag_answer" in st.session_state:
    st.divider()
    st.subheader("Answer")
    st.markdown(st.session_state["rag_answer"])

    st.caption(
        f"Routed department: {st.session_state['rag_department']}"
    )

    st.subheader("Sources")
    sources = st.session_state["rag_sources"]

    if sources:
        for source in sources:
            st.markdown(f"- `{source}`")
    else:
        st.info("No relevant source documents were returned.")
