import os
import requests
import streamlit as st

# -----------------------------------------------------------------------------
# Configuration & Backend Setup
# -----------------------------------------------------------------------------
API_URL = os.getenv("RAG_API_URL", "http://localhost:8001").rstrip("/")
QUERY_URL = f"{API_URL}/query"

st.set_page_config(
    page_title="Enterprise RAG Assistant",
    page_icon="📚",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -----------------------------------------------------------------------------
# Custom CSS for Professional Slate-Blue Styling & Layout
# -----------------------------------------------------------------------------
st.markdown(
    """
    <style>
    /* Main app styling */
    .stApp {
        background-color: #F8FAFC;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }

    /* Sidebar Styling */
    [data-testid="stSidebar"] {
        background-color: #F1F5F9;
        border-right: 1px solid #E2E8F0;
    }

    /* Primary Search Button Styling */
    div.stButton > button:first-child, div[data-testid="stFormSubmitButton"] > button {
        background-color: #1E3A5F !important;
        color: #FFFFFF !important;
        border: none !important;
        border-radius: 6px !important;
        font-weight: 600 !important;
        padding: 0.5rem 1rem !important;
        transition: all 0.2s ease-in-out;
    }
    div.stButton > button:first-child:hover, div[data-testid="stFormSubmitButton"] > button:hover {
        background-color: #2D4A77 !important;
        color: #FFFFFF !important;
    }

    /* Routed Department Badge */
    .dept-badge {
        display: inline-block;
        background-color: #E0E7FF;
        color: #3730A3;
        font-size: 0.8rem;
        font-weight: 600;
        padding: 0.25rem 0.6rem;
        border-radius: 4px;
        margin-bottom: 0.6rem;
        border: 1px solid #C7D2FE;
    }

    /* Source Tags / Chips */
    .source-chip {
        display: inline-block;
        background-color: #FEF3C7;
        color: #92400E;
        padding: 0.2rem 0.6rem;
        border-radius: 4px;
        font-family: monospace;
        font-size: 0.85rem;
        margin-right: 0.5rem;
        margin-top: 0.3rem;
        border: 1px solid #FDE68A;
    }

    /* Chat message spacing */
    .stChatMessage {
        background-color: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 8px;
        padding: 1rem;
        margin-bottom: 0.75rem;
        box-shadow: 0 1px 2px rgba(0,0,0,0.03);
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# -----------------------------------------------------------------------------
# SIDEBAR (Exact match to your layout & options)
# -----------------------------------------------------------------------------
with st.sidebar:
    st.header("Search settings")

    st.selectbox(
        "Department",
        ["All Departments", "HR", "Finance", "Legal", "Customer"],
        key="department_filter",
    )

    st.caption("Answers are generated by the connected RAG backend.")
    st.caption(f"Backend: [{API_URL}]({API_URL})")

# -----------------------------------------------------------------------------
# MAIN CONTENT HEADER
# -----------------------------------------------------------------------------
st.title("📚 Enterprise RAG Assistant")
st.caption("Ask questions across HR, Finance, Legal, and Customer documents.")

# Initialize Chat History in Session State
if "messages" not in st.session_state:
    st.session_state["messages"] = [
        {
            "role": "assistant",
            "content": "Welcome! Ask any question regarding company policies or internal documents.",
            "department": None,
            "sources": [],
        }
    ]

# -----------------------------------------------------------------------------
# RENDER CHAT HISTORY (Uses "R" and "H" Avatars)
# -----------------------------------------------------------------------------
for msg in st.session_state["messages"]:
    avatar_logo = "H" if msg["role"] == "user" else "R"
    with st.chat_message(msg["role"], avatar=avatar_logo):
        # Render Routed Department badge if present
        if msg.get("department"):
            st.markdown(
                f'<span class="dept-badge">Routed department: {msg["department"]}</span>',
                unsafe_allow_html=True,
            )

        # Render Answer/Content
        st.markdown(msg["content"])

        # Render Sources list if available
        sources = msg.get("sources", [])
        if sources:
            st.markdown("**Sources**")
            source_html = "".join(
                [f'<span class="source-chip">{s}</span>' for s in sources]
            )
            st.markdown(source_html, unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# INPUT CONTAINER & SEARCH BUTTON
# -----------------------------------------------------------------------------
with st.form(key="chat_search_form", clear_on_submit=True):
    col_input, col_button = st.columns([5, 1])

    with col_input:
        user_query = st.text_input(
            "Question input",
            placeholder='Enter question about documents (e.g., "What is the leave policy?")',
            label_visibility="collapsed",
        )

    with col_button:
        submit_search = st.form_submit_button(
            "Search", type="primary", use_container_width=True
        )

# -----------------------------------------------------------------------------
# QUERY EXECUTION & BACKEND CALL
# -----------------------------------------------------------------------------
if submit_search:
    question = user_query.strip()

    if not question:
        st.warning("Please enter a question first.")
    else:
        # 1. Add User Question to Chat History & Display Immediately
        st.session_state["messages"].append({"role": "user", "content": question})
        with st.chat_message("user", avatar="H"):
            st.markdown(question)

        # 2. Call Backend RAG Service with Spinner
        with st.chat_message("assistant", avatar="R"):
            with st.spinner(
                "Searching documents and generating an answer… "
                "This may take 15–60 seconds."
            ):
                try:
                    response = requests.post(
                        QUERY_URL,
                        json={"question": question},
                        timeout=120,
                    )

                    if response.status_code == 200:
                        data = response.json()

                        answer = data.get("answer", "No answer was returned.")
                        department = data.get("department", "unknown")
                        sources = data.get("sources", [])

                        # Render Department Badge
                        st.markdown(
                            f'<span class="dept-badge">Routed department: {department}</span>',
                            unsafe_allow_html=True,
                        )

                        # Render Formatted Markdown Answer
                        st.markdown(answer)

                        # Render Sources
                        if sources:
                            st.markdown("**Sources**")
                            source_html = "".join(
                                [
                                    f'<span class="source-chip">{s}</span>'
                                    for s in sources
                                ]
                            )
                            st.markdown(source_html, unsafe_allow_html=True)
                        else:
                            st.info("No relevant source documents were returned.")

                        # Append Assistant Response to Chat History
                        st.session_state["messages"].append(
                            {
                                "role": "assistant",
                                "content": answer,
                                "department": department,
                                "sources": sources,
                            }
                        )

                    else:
                        st.error(
                            f"Backend error (HTTP {response.status_code}). "
                            "Please try again."
                        )

                except requests.exceptions.ConnectionError:
                    st.error(
                        "Can't reach the RAG server. "
                        "Please check that the backend is running on port 8001."
                    )

                except requests.exceptions.Timeout:
                    st.error(
                        "The request took too long. "
                        "Please check the backend and try again."
                    )

                except requests.exceptions.RequestException:
                    st.error("Something went wrong while contacting the backend.")

                except ValueError:
                    st.error("The backend returned an invalid response.")
